### ISSUE TITLE
Filter down to RTP only

### ISSUE THREAD

**Issue by nils-ohlmeier** [fippo/webrtc-dump-importer#10]
Most of the time the graphs for ICE candidates and ports etc are just noise. So it would be helpful to filter by default down to anything related to RTP. Maybe with the option to include the ICE graphs later.

**Comment by fippo** [comment]
oh yes... also a more defined order of graphs. currently it is whatever order getstats returns i think

**Comment by fippo** [comment]
years later... I have a WIP webrtc-internals change for this:
  https://chromium-review.googlesource.com/c/chromium/src/+/4001712
but still pondering how exactly this should work, also here. Here it is easier because we already can filter individual lines from the graph so the CL might work as is :-)
